"""Run network calls in a subprocess to avoid Blender's main-thread SSL stalls.

Blender's bundled Python performs SSL handshakes that hold the GIL long enough
to freeze the UI. Spawning a subprocess sidesteps the issue: the worker does
all I/O, writes the binary result to a temp file, and prints a small JSON
status line on stdout.

Provider implementations call `run_subprocess(worker_script, config)` with a
short Python source string and a JSON-serialisable config dict. The helper
takes care of:

  * Allocating a temp output file and passing its path in `config["output_path"]`.
  * Running the worker, enforcing a timeout.
  * Parsing the worker's JSON stdout.
  * Mapping HTTP error codes (401/403/429) to the right exception class.
  * Reading the binary result back off disk and returning it.

The worker script must:

  * Read JSON from stdin.
  * Write the generated bytes to `config["output_path"]`.
  * Print a JSON object on stdout, e.g. `{"seed": 12345}` for success or
    `{"error": "..."}` for failure.
"""

from __future__ import annotations

import json
import os
import subprocess
import sys
import tempfile

from .api import (
    AuthenticationError,
    ContentFilterError,
    ProviderError,
    RateLimitError,
)


def run_subprocess(
    worker_script: str,
    config: dict,
    *,
    timeout: int = 360,
    output_suffix: str = ".png",
) -> dict:
    """Execute `worker_script` in a subprocess; return the parsed result.

    On success the returned dict will contain:
        image_bytes: bytes  -- contents of the temp output file
        ...whatever else the worker put on stdout (e.g. seed, size)

    On failure raises a `ProviderError` subclass.
    """
    out_fd, out_path = tempfile.mkstemp(suffix=output_suffix)
    os.close(out_fd)
    config = {**config, "output_path": out_path}

    try:
        proc = subprocess.run(
            [sys.executable, "-c", worker_script],
            input=json.dumps(config),
            capture_output=True, text=True,
            timeout=timeout,
        )
    except subprocess.TimeoutExpired:
        _cleanup(out_path)
        raise ProviderError("Generation timed out")
    except Exception as e:
        _cleanup(out_path)
        raise ProviderError(f"Subprocess error: {e}")

    if proc.returncode != 0:
        _cleanup(out_path)
        raise ProviderError(
            f"Worker exited with code {proc.returncode}: {proc.stderr[:500]}"
        )

    stdout = proc.stdout.strip()
    if not stdout:
        _cleanup(out_path)
        raise ProviderError(f"No output from worker. stderr: {proc.stderr[:500]}")

    try:
        result = json.loads(stdout)
    except json.JSONDecodeError:
        _cleanup(out_path)
        raise ProviderError(f"Invalid worker output: {stdout[:200]}")

    if "error" in result:
        _cleanup(out_path)
        _raise_for_error(result["error"])

    try:
        with open(out_path, "rb") as f:
            result["image_bytes"] = f.read()
    finally:
        _cleanup(out_path)

    return result


def _raise_for_error(msg: str):
    if "401" in msg or "403" in msg or "Unauthorized" in msg:
        raise AuthenticationError(msg)
    if "429" in msg or "rate" in msg.lower():
        raise RateLimitError(msg)
    if "filter" in msg.lower() or "safety" in msg.lower():
        raise ContentFilterError(msg)
    raise ProviderError(msg)


def _cleanup(path: str):
    try:
        os.unlink(path)
    except OSError:
        pass
