"""Run network calls in a subprocess to avoid Blender's main-thread SSL stalls.

Blender's bundled Python performs SSL handshakes that hold the GIL long enough
to freeze the UI. Spawning a subprocess sidesteps the issue: the worker does
all I/O, writes the binary result to a temp file, and prints a small JSON
status line on stdout.

Provider implementations call `run_subprocess(worker_script, config)` with a
short Python source string and a JSON-serialisable config dict. The helper
takes care of:

  * Allocating a temp output file and passing its path in `config["output_path"]`.
  * Running the worker, enforcing a timeout.
  * Parsing the worker's JSON stdout.
  * Mapping HTTP error codes (401/403/429) to the right exception class.
  * Reading the binary result back off disk and returning it.

The worker script must:

  * Read JSON from stdin.
  * Write the generated bytes to `config["output_path"]`.
  * Print a JSON object on stdout, e.g. `{"seed": 12345}` for success or
    `{"error": "..."}` for failure.
"""

from __future__ import annotations

import json
import os
import subprocess
import sys
import tempfile
import threading

from .api import (
    AuthenticationError,
    ContentFilterError,
    ProviderError,
    RateLimitError,
)


# Registry of in-flight worker subprocesses so a pipeline cancel can kill them
# immediately, instead of waiting out the (possibly minutes-long) request.
_active_procs: set[subprocess.Popen] = set()
_procs_lock = threading.Lock()
_cancel_requested = False


def request_cancel():
    """Kill any in-flight worker subprocess. Called by the cancel operator."""
    global _cancel_requested
    _cancel_requested = True
    with _procs_lock:
        for p in list(_active_procs):
            try:
                p.kill()
            except Exception:
                pass


def reset_cancel():
    """Clear the cancel latch at the start of a fresh run."""
    global _cancel_requested
    _cancel_requested = False


def run_subprocess(
    worker_script: str,
    config: dict,
    *,
    timeout: int = 360,
    output_suffix: str = ".png",
) -> dict:
    """Execute `worker_script` in a subprocess; return the parsed result.

    On success the returned dict will contain:
        image_bytes: bytes  -- contents of the temp output file
        ...whatever else the worker put on stdout (e.g. seed, size)

    On failure raises a `ProviderError` subclass.
    """
    out_fd, out_path = tempfile.mkstemp(suffix=output_suffix)
    os.close(out_fd)
    config = {**config, "output_path": out_path}

    try:
        proc = subprocess.Popen(
            [sys.executable, "-c", worker_script],
            stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE,
            text=True,
        )
    except Exception as e:
        _cleanup(out_path)
        raise ProviderError(f"Subprocess error: {e}")

    # Register so a UI cancel can kill this mid-request. If a cancel raced in
    # before we registered, kill right away.
    with _procs_lock:
        _active_procs.add(proc)
    if _cancel_requested:
        try:
            proc.kill()
        except Exception:
            pass

    try:
        out, err = proc.communicate(input=json.dumps(config), timeout=timeout)
    except subprocess.TimeoutExpired:
        proc.kill()
        proc.communicate()
        _cleanup(out_path)
        raise ProviderError("Generation timed out")
    except Exception as e:
        _cleanup(out_path)
        raise ProviderError(f"Subprocess error: {e}")
    finally:
        with _procs_lock:
            _active_procs.discard(proc)

    if _cancel_requested:
        _cleanup(out_path)
        raise ProviderError("Cancelled")

    if proc.returncode != 0:
        _cleanup(out_path)
        raise ProviderError(
            f"Worker exited with code {proc.returncode}: {err[:2000]}"
        )

    stdout = out.strip()
    if not stdout:
        _cleanup(out_path)
        raise ProviderError(f"No output from worker. stderr: {err[:2000]}")

    try:
        result = json.loads(stdout)
    except json.JSONDecodeError:
        _cleanup(out_path)
        raise ProviderError(f"Invalid worker output: {stdout[:200]}")

    if "error" in result:
        _cleanup(out_path)
        _raise_for_error(result["error"])

    try:
        with open(out_path, "rb") as f:
            result["image_bytes"] = f.read()
    finally:
        _cleanup(out_path)

    return result


def _raise_for_error(msg: str):
    if "401" in msg or "403" in msg or "Unauthorized" in msg:
        raise AuthenticationError(msg)
    if "429" in msg or "rate" in msg.lower():
        raise RateLimitError(msg)
    if "filter" in msg.lower() or "safety" in msg.lower():
        raise ContentFilterError(msg)
    raise ProviderError(msg)


def _cleanup(path: str):
    try:
        os.unlink(path)
    except OSError:
        pass
